# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('time', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
