# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='symbol',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
