# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_auto_20151226_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
