# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20151226_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='symbol',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
