# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20151226_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='time',
            field=models.DateField(blank=True),
        ),
    ]
