# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_auto_20151226_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='class1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u65b9\u5f0f'),
        ),
        migrations.AlterField(
            model_name='case',
            name='class2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u73af\u8282'),
        ),
        migrations.AlterField(
            model_name='case',
            name='class3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u4f53'),
        ),
        migrations.AlterField(
            model_name='case',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='symbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e3b\u9898'),
        ),
        migrations.AlterField(
            model_name='case',
            name='words',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
